apiVersion: v1
kind: Service
metadata:
  name: sso-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sso-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-k8s
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sso-k8s
  template:
    metadata:
      labels:
        app: sso-k8s
    spec:
      containers:
        - name: sso-k8s
          image: CONTAINER_IMAGE
          env:
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "TeknoBuilt123"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "TeknoBuilt123"
            - name: POSTGRES_PORT_5432_TCP_ADDR
              value: "keycloaksso.cst6fbronkql.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_PORT_5432_TCP_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: "postgres"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
