apiVersion: v1
kind: Service
metadata:
  name: sso-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sso-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-k8s
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sso-k8s
  template:
    metadata:
      labels:
        app: sso-k8s
    spec:
      containers:
        - name: sso-k8s
          image: 176023829637.dkr.ecr.us-east-1.amazonaws.com/test_poc:master.dev.2020-08-24.17.29.58.29494eaa
          ports:
            - containerPort: 8080
